"""Human-review PR gate — opens a git PR for generated/healed diffs.

Generated or healed page objects and test files are committed to a branch
and a PR is opened for human review before merge.
"""

from __future__ import annotations

import asyncio
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


async def _run_git(*args: str, cwd: str | None = None) -> tuple[int, str, str]:
    """Run a git command and return (returncode, stdout, stderr)."""
    proc = await asyncio.create_subprocess_exec(
        "git", *args,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        cwd=cwd or str(_PROJECT_ROOT),
    )
    stdout, stderr = await proc.communicate()
    return (
        proc.returncode or 0,
        stdout.decode("utf-8", errors="replace").strip(),
        stderr.decode("utf-8", errors="replace").strip(),
    )


async def open_review_pr(
    branch_name: str,
    title: str,
    body: str,
    files: list[str],
    base_branch: str = "main",
) -> dict[str, Any]:
    """Create a branch, commit changed files, push, and open a PR via `gh`.

    Args:
        branch_name: Name for the feature branch.
        title: PR title.
        body: PR description (markdown).
        files: List of file paths to stage and commit.
        base_branch: Branch to open the PR against.

    Returns:
        {"status": "created"|"error", "pr_url": "...", "branch": "..."}
    """
    # 1. Create and checkout branch
    rc, _, err = await _run_git("checkout", "-b", branch_name)
    if rc != 0:
        # Branch may already exist
        rc, _, err = await _run_git("checkout", branch_name)
        if rc != 0:
            logger.error("PR gate: failed to create branch %s: %s", branch_name, err)
            return {"status": "error", "error": err}

    # 2. Stage files
    for f in files:
        rc, _, err = await _run_git("add", f)
        if rc != 0:
            logger.warning("PR gate: failed to stage %s: %s", f, err)

    # 3. Commit
    commit_msg = f"[qa-agent] {title}\n\nAuto-generated by QA Agent."
    rc, _, err = await _run_git("commit", "-m", commit_msg)
    if rc != 0:
        logger.error("PR gate: commit failed: %s", err)
        return {"status": "error", "error": f"Commit failed: {err}"}

    # 4. Push
    rc, _, err = await _run_git("push", "-u", "origin", branch_name)
    if rc != 0:
        logger.error("PR gate: push failed: %s", err)
        return {"status": "error", "error": f"Push failed: {err}"}

    # 5. Open PR via gh CLI
    pr_result = await _open_gh_pr(branch_name, base_branch, title, body)
    return pr_result


async def _open_gh_pr(
    head: str,
    base: str,
    title: str,
    body: str,
) -> dict[str, Any]:
    """Open a PR using the GitHub CLI (`gh`)."""
    proc = await asyncio.create_subprocess_exec(
        "gh", "pr", "create",
        "--head", head,
        "--base", base,
        "--title", title,
        "--body", body,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        cwd=str(_PROJECT_ROOT),
    )
    stdout, stderr = await proc.communicate()
    stdout_str = stdout.decode("utf-8", errors="replace").strip()
    stderr_str = stderr.decode("utf-8", errors="replace").strip()

    if proc.returncode == 0:
        pr_url = stdout_str
        logger.info("PR gate: opened PR %s", pr_url)
        return {"status": "created", "pr_url": pr_url, "branch": head}

    logger.error("PR gate: gh pr create failed: %s", stderr_str)
    return {"status": "error", "error": stderr_str}


def build_pr_body(
    goal: str,
    changes: list[dict[str, str]],
    outcome: str,
) -> str:
    """Build a markdown PR body describing the changes."""
    lines = [
        "## QA Agent — Auto-generated Changes\n",
        f"**Goal:** {goal}\n",
        f"**Outcome:** {outcome}\n",
        "### Changed files\n",
    ]
    for change in changes:
        lines.append(f"- `{change.get('file', '?')}` — {change.get('reason', 'updated')}")

    lines.extend([
        "\n---",
        "*This PR was auto-generated by the QA Agent. "
        "Please review the changes before merging.*",
    ])
    return "\n".join(lines)
